name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin
          - cmucl
          - alisp
        os: [ ubuntu-20.04, ubuntu-18.04 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Roswell
        uses: 40b/setup-roswell@v1
        with:
          lisp: ${{ matrix.lisp }}

      - name: Cache Roswell
        uses: actions/cache@v4
        with:
          path: ~/.roswell
          key: ${{ runner.os }}-roswell-${{ matrix.lisp }}-${{ hashFiles('**/*.asd') }}
          restore-keys: |
            ${{ runner.os }}-roswell-${{ matrix.lisp }}-

      - name: Make test script executable
        run: chmod +x ./testscr.ros

      - name: Run tests
        run: ./testscr.ros
