name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: ${{ matrix.lisp }} on ${{ matrix.os }}
    strategy:
      matrix:
        lisp:
          - abcl-bin
          - ccl-bin
          - clasp
          - clisp
          - cmu-bin
          - ecl
          - sbcl-bin
        os: [ ubuntu-24.04, ubuntu-22.04, ubuntu-20.04, ubuntu-18.04 ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Roswell
        uses: actions/cache@v4
        with:
          path: ~/.roswell
          key: ${{ runner.os }}-roswell-${{ matrix.lisp }}-${{ hashFiles('**/*.asd') }}
          restore-keys: |
            ${{ runner.os }}-roswell-${{ matrix.lisp }}-

      - name: Install Roswell
        env:
          LISP: ${{ matrix.lisp }}
        run: curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh

      - name: Make test script executable
        run: chmod +x ./testscr.ros

      - name: Run tests
        run: ./testscr.ros
